environmentType: dev
githubRepoName: aime-platform-auth-ms
githubRepoOwner: theaimegroup
githubAccessTokenName: github-access-token-secret

dev:
  stackName: test-platform-auth-ms-dev-backend-stack
  branch: main
  pipelineBucket: codepipeline-eu-west-2-975428383503
  pipelineConfig:
    name: test-platform-auth-ms-dev-backend-pipeline
  minSize: 1
  maxSize: 1
  instanceTypes: t2.micro
  ebEnvName: test-platform-auth-ms-dev-env
  ebAppName: test-platform-auth-ms-dev-app
